---
- name: Playbook to manage elnappos dotfiles (https://github.com/elnappo/dotfiles)
  hosts: localhost
  vars:
    osx_login_shell: /usr/local/bin/zsh
    sudo_without_password: true
  connection: local
  tasks:
    - name: make sure dotfiles are present
      git: repo=https://github.com/elnappo/dotfiles.git dest=~/.dotfiles

    - name: allow sudo without password
      lineinfile: 'dest=/etc/sudoers state=present line="{{ ansible_user_id }}	ALL=NOPASSWD: ALL" insertafter="^%admin\tALL=\(ALL\) ALL" validate="visudo -cf %s"'
      sudo: yes
      when: sudo_without_password

    - name: add localdocker to /etc/hosts (for boot2docker)
      lineinfile: dest=/etc/hosts line="192.168.59.103 localdocker" state=present
      sudo: yes

    - name: create oh-my-zsh customization directory
      file: dest=~/.dotfiles/zsh_custom/plugins state=directory

    - name: install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh update=yes

    - name: install alias-tips
      git: repo=https://github.com/djui/alias-tips.git dest=~/.dotfiles/zsh_custom/plugins/alias-tips update=yes

    - name: install k
      git: repo=https://github.com/supercrabtree/k.git dest=~/.dotfiles/zsh_custom/plugins/k update=yes

    - name: install neobundle
      git: repo=https://github.com/Shougo/neobundle.vim dest=~/.dotfiles/vim/bundle/neobundle.vim update=yes

    - name: create ~/.virtualenvs
      file: dest=~/.virtualenvs state=directory

    - include: tasks/link_files.yml tags=links
    - include: tasks/packages.yml tags=packages
    - include: tasks/shells.yml tags=shells
