---
- hosts: localhost
  connection: local
  tasks:
    - name: add localdocker to /etc/hosts
      lineinfile: dest=/etc/hosts line="192.168.59.103 localdocker" state=present
      sudo: yes

    - name: add homwbrew bash to /etc/shells
      lineinfile: dest=/etc/shells line="/usr/local/bin/bash" state=present
      sudo: yes

    - name: add homwbrew zsh to /etc/shells
      lineinfile: dest=/etc/shells line="/usr/local/bin/zsh" state=present
      sudo: yes

    - name: create oh-my-zsh customization directory
      file: dest=~/.dotfiles/zsh_custom/plugins state=directory

    - name: install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh update=yes

    - name: install alias-tips
      git: repo=https://github.com/djui/alias-tips.git dest=~/.dotfiles/zsh_custom/plugins/alias-tips update=yes

    - name: install k
      git: repo=https://github.com/supercrabtree/k.git dest=~/.dotfiles/zsh_custom/plugins/k update=yes

    - name: make sure dotfiles are present
      git: repo=git@github.com:elnappo/dotfiles.git dest=~/.dotfiles

    - name: link bashrc
      file: src=~/.dotfiles/bashrc dest=~/.bashrc state=link

    - name: link zshrc
      file: src=~/.dotfiles/zshrc dest=~/.zshrc state=link

    - name: link wgetrc
      file: src=~/.dotfiles/wgetrc dest=~/.wgetrc state=link

    - name: link vimrc
      file: src=~/.dotfiles/vimrc dest=~/.vimrc state=link

    - name: link curlrc
      file: src=~/.dotfiles/curlrc dest=~/.curlrc state=link

    - name: create ~/.virtualenvs
      file: dest=~/.virtualenvs state=directory

    - include: tasks/homebrew.yml
