---
os: osx
osx_image: xcode10
install:
  - brew upgrade ansible
  - ansible --version
before_script:
  - rm ~/.bashrc
  - rm ~/.bash_profile
  - brew doctor || true
script:
  - ansible-playbook --syntax-check --list-tasks ansible/dotfiles.yml
  - ansible-playbook ansible/dotfiles.yml --skip-tags "packages,dnscrypt"
  - >
    ansible-playbook ansible/dotfiles.yml --skip-tags "packages,dnscrypt"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
after_script:
  - brew doctor || true
  - brew list
  - brew cleanup
  - ls -la ~/
