---
language:
  - objective-c
install:
  - brew install ansible
  - ansible --version
  - ls -la /Users/travis/.dotfiles
script:
  - ansible-playbook -i init/inventory --syntax-check --list-tasks init/dotfiles.yml
  - ansible-playbook -i init/inventory init/dotfiles.yml
  - >
    ansible-playbook -i init/inventory init/dotfiles.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

