---
os: osx
osx_image: xcode9.1
install:
  - brew install ansible
  - ansible --version
before_script:
  - rm ~/.bashrc
  - rm ~/.bash_profile
  - rm ~/.zshrc
  - brew doctor || true
script:
  - ansible-playbook -i ansible/inventory --syntax-check --list-tasks ansible/dotfiles.yml
  - ansible-playbook -i ansible/inventory ansible/dotfiles.yml --skip-tags "packages"
  - >
    ansible-playbook -i ansible/inventory ansible/dotfiles.yml --skip-tags "packages"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
after_script:
  - brew doctor || true
  - brew list
  - brew cleanup
  - brew cask cleanup
  - ls -la ~/
