---
formula:
  ack:
  ansible:
  archey4:
  axel:
  bash-completion:
  bash:
  bat:
  binwalk:
  coreutils:
  cowsay:
  ddrescue:
  fd:
  findutils:
  fish:
  fzf:
  go:
  grc:
  grep:
  htop:
  httpie:
  hub:
  iftop:
  iproute2mac:
  jq:
  kubernetes-cli:
  kubernetes-helm:
  libusb:
  lnav:
  moreutils:
  mtr:
  ncdu:
  nikto:
  nmap:
  openssl:
  peco:
  pwgen:
  python:
  rename:
  shellcheck:
  smartmontools:
  ssh-copy-id:
  telnet:
  tmux:
  tree:
  unp:
  vim:
    options: override-system-vi,with-lua,with-luajit
  watch:
  wget:
  youtube-dl:
  zsh:
