---
pacman:
  # CLI
  wget:
  openssh:
  vim:
  vte3-ng:
  hydra:
  john:
  masscan:
  zmap:
  nikto:
  openssl:
  bash:
  bash-completion:
  zsh:
  fish:
  coreutils:
  moreutils:
  findutils:
  grep:
  ack:
  tree:
  p7zip:
  cowsay:
  nmap:
  htop:
  unp:
  speedtest-cli:
  axel:
  python:
  python2:
  python-pip:
  python2-pip:
  python-setuptools:
  python2-setuptools:
  ruby:
  go:
  iftop:
  tor:
  torsocks:
  youtube-dl:
  pwgen:
  archey3:
  ansible:
  httpie:
  grc:
  smartmontools:
  mtr:
  ncdu:
  tmux:
  syncthing:
  binwalk:
  ddrescue:
  hub:
  vagrant:
  docker:
  unrar:
  openvpn:
  redshift:
  pkgfile:
  cups:
  pulseaudio-alsa:
  pkgstats:
  numlockx:
  mlocate:
  ttf-dejavu:
  ttf-ionicons:
  adobe-source-code-pro-fonts:
  ttf-ubuntu-font-family:
  util-linux:
  ufw:
  netcat:
  net-tools:

  # GUI
  xorg-server:
  xorg-xinit:
  compton:
  pavucontrol:
  gdm:
  i3:
  feh:
  dmenu:
  gnome:
  gnome-extra:
  gnome-search-tool:
  gnome-icon-theme:
  arc-gtk-theme:
  arc-icon-theme:
  terminator:
  termite:
  nautilus:
  sushi:
  thunar:
  thunar-archive-plugin:
  thunar-media-tags-plugin:
  thunar-volman:
  lxappearance:
  i3status:
  gnome-keyring:
  libsecret:
  seahorse:
  chromium:
  firefox:
  thunderbird:
  transmission-gtk:
  vlc:
  libreoffice-fresh:
  wireshark-gtk:
  pidgin:
  pidgin-otr:
  pidgin-libnotify:
  purple-plugin-pack:

