---
- block:
  - name: Configure pacman
    lineinfile:
      path: /etc/pacman.conf
      line: "{{ item.line }}"
      regexp: "{{ item.regexp }}"
      backrefs: "{{ item.backrefs }}"
    loop:
      - { line: "Color", regexp: "#Color", backrefs: true}
      - { line: "ILoveCandy", regexp: "#ILoveCandy", backrefs: true}

  - name: Enable Multilib
    ini_file:
      path: /etc/pacman.conf
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value | default(omit) }}"
    loop:
      - { section: "multilib", option: "Include", value: "/etc/pacman.d/mirrorlist" }

  - name: Enable pkgfile update timer
    systemd:
      name: pkgfile-update.timer
      enabled: true
      state: started

  - name: Add user to wheel and wireshark group
    user:
      name: "{{ ansible_user_id }}"
      groups: wheel,wireshark
      append: true

  - name: Add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: true
    when: sudo_without_password

  become: true
