---
- block:
  - name: Configure pacman
    lineinfile: path=/etc/pacman.conf line="Color" regexp="#Color" backrefs=yes

  - name: Enable Multilib
    ini_file: path=/etc/pacman.conf section={{ item.section }} option={{ item.option }} value={{ item.value | default(omit) }}
    with_items:
      - { section: "multilib", option: "Include", value: "/etc/pacman.d/mirrorlist" }

  - name: Enable pkgfile update timer
    systemd: name=pkgfile-update.timer enabled=True state=started
  
  - name: Add user to wireshark group
    user: name={{ ansible_user_id }} groups=wireshark

  become: yes
