---
- name: Install dnsmasq and dnscrypt-proxy
  package:
    name: dnscrypt-proxy
    state: present

- name: Configure dnscrypt-proxy
  ini_file:
    path: /usr/local/etc/dnscrypt-proxy.toml
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - { section: "", option: "server_names", value: "['cloudflare', 'google']" }
    - { section: "", option: "require_dnssec", value: "true" }
    - { section: "", option: "cache_size", value: "2560" }
  register: config_change

- name: Start dnscrypt-proxy
  command: brew services restart dnscrypt-proxy
  when: config_change.changed
  become: yes
