---
- name: Install dnsmasq and dnscrypt-proxy
  homebrew: name={{ item }} state=present
  with_items:
    - dnsmasq
    - dnscrypt-proxy

- name: Configure dnsmasq and dnscrypt-proxy
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "files/dnsmasq.conf", dest: "/usr/local/etc/dnsmasq.conf" }
    - { src: "files/dnscrypt-proxy.conf", dest: "/usr/local/etc/dnscrypt-proxy.conf" }
  register: config_change

- name: Start services
  command: brew services restart {{ item }}
  with_items:
    - dnscrypt-proxy
    - dnsmasq
  when: config_change.changed
  become: yes
