---
- name: Install dnsmasq and dnscrypt-proxy
  package:
    name: dnscrypt-proxy
    state: present

- name: Configure dnscrypt-proxy
  ini_file:
    path: /opt/homebrew/etc/dnscrypt-proxy.toml
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  loop:
    - { section: "", option: "server_names", value: "['cloudflare', 'google']" }
    - { section: "", option: "listen_addresses", value: "['127.0.0.1:53', '[::1]:53']" }
    - { section: "", option: "require_dnssec", value: "true" }
    - { section: "", option: "cache_size", value: "2560" }
    - { section: "", option: "odoh_servers", value: "true" }
  register: config_change

- name: Start dnscrypt-proxy
  command: brew services restart dnscrypt-proxy
  when: config_change.changed
  become: yes
