---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.dotfiles/bash_profile", dest: "~/.bash_profile"}
    - { src: "~/.dotfiles/bashrc", dest: "~/.bashrc"}
    - { src: "~/.dotfiles/config/vscode/settings.json", dest: "~/Library/Application Support/Code/User/settings.json" }
    - { src: "~/.dotfiles/vimrc", dest: "~/.vimrc"}
    - { src: "~/.dotfiles/wgetrc", dest: "~/.wgetrc"}
    - { src: "~/.dotfiles/zshrc", dest: "~/.zshrc"}
