---
- name: Playbook to manage elnappos dotfiles (https://github.com/elnappo/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ../vars.yml
      tags:
        - always

    - name: Make sure dotfiles are present
      git:
        repo: https://github.com/JonasGoetz01/dotfiles-new.git
        dest: ~/.dotfiles

    - name: Allow sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "{{ ansible_user_id }}	ALL=NOPASSWD: ALL"
        insertafter:  '^%admin\tALL=\(ALL\) ALL'
        validate: "visudo -cf %s"
      become: yes
      when: sudo_without_password and ansible_os_family == "Darwin"

    - name: Enable tty_tickets
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "Defaults tty_tickets"
        validate: "visudo -cf %s"
      become: yes
      when: ansible_os_family == "Darwin"

    - name: Create folder
      file:
        path: "{{item}}"
        state: directory
      loop:
        - "~/workspace/"

    - include_tasks: tasks/link_files.yml
      tags:
        - links

    - include_tasks: tasks/packages.yml
      tags:
        - packages

    - name: Install iTerm 2 shell integrations
      get_url:
        url: https://iterm2.com/shell_integration/{{item}}
        dest: ~/.local/share/{{item}}/iterm2_shell_integration.{{item}}
      loop:
        - "zsh"
        - "bash"
      when: ansible_os_family == "Darwin"

    # Needs to be after packages
    - include_tasks: tasks/shells.yml
      tags:
        - shells

    - include_tasks: tasks/macos_defaults.yml
      when: ansible_os_family == "Darwin"
      tags:
        - macos_defaults

  handlers:
    - name: Kill Dock
      command: killall Dock

    - name: Kill Finder
      command: killall Finder

    - name: Kill Transmission
      command: killall Transmission
      ignore_errors: yes

    - name: Kill Safari
      command: killall Safari
      ignore_errors: yes

    - name: Kill Terminal
      command: killall Terminal
      ignore_errors: yes

    - name: Kill WindowManager
      command: killall WindowManager
      ignore_errors: yes
