---
- name: Include taps list
  include_vars: files/taps.yml
  tags: packages

- name: Include formula list
  include_vars: files/formula.yml
  tags: packages

- name: Include casks list
  include_vars: files/casks.yml
  tags: packages

- name: Update/Upgrade Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes
  tags: packages

- name: Manage taps
  homebrew_tap: name={{ item.key }} state={{ item.value.state | default("present") }}
  with_dict: taps
  tags: packages

- name: Manage formula
  homebrew: name={{ item.key }} install_options={{ item.value.options | default(omit) }} state={{ item.value.state | default("present") }}
  with_dict: formula
  tags: packages

- name: Manage casks
  homebrew_cask: name={{ item.key }} state={{ item.value.state | default("present") }}
  with_dict: casks
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
  tags: packages
